# Generated by Django 5.1 on 2024-10-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_content_post_body_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='created at'),
        ),
    ]
