# Generated by Django 5.1 on 2024-10-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='self_introduction',
            field=models.TextField(default=' '),
        ),
    ]
