# Generated by Django 5.1 on 2024-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_profile_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
