# Generated by Django 5.1 on 2024-12-11 02:48

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.rename_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_introduction',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
