# Generated by Django 5.1 on 2024-12-12 02:21

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_profile_bg_image_alter_post_user_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='', null=True, upload_to=post.models.rename_bg_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='E:\\6-16\\socialmedia\\media\\profiles\\images\\default.png', null=True, upload_to=post.models.rename_image),
        ),
    ]
