# Generated by Django 5.1.4 on 2024-12-27 07:34

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_profile_bg_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='D:\\6-16\\socialmedia\\media\\profiles\\images\\default.png', null=True, upload_to=post.models.rename_image),
        ),
    ]
