# Generated by Django 5.1 on 2024-11-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitChat', '0004_room_users_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
