# Generated by Django 5.1 on 2024-12-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
